JFLAGS = -cp "/home/eetlabs.local/sint/sint86/apache-tomcat-9.0.12/lib/*"
JC = javac

CLASSES = Cancion.java Disco.java Sint86P2.java

default: classes

classes:
	$(JC) $(JFLAGS) $(CLASSES)

clean:
		$(RM) *.class
